services:
  users:
    broker: tcp://localhost:5555
    db:
      name: users
      client: schemaless
    clients:
      - mail
      - sms
    workers: 5
  # zones:
  #   addr: tcp://localhost:5556
  #   workers: 2
  # mail:
  #   broker: tcp://localhost:5557
  #   workers: 2
  # sms:
  #   broker: tcp://localhost:5558
  #   workers: 2
gateway:
  workers: 4
  clients:
    - users
    #- zones
