verbose: True

brokers:
  mail: tcp://127.0.0.1:5557
  users: tcp://127.0.0.1:5555

services:
  mail:
    workers: 2
  users:
    db: schemaless
    clients:
      - mail
    workers: 5

gateway:
  workers: 4
